language: ruby
before_install:
  - gem update bundler
  - gem update --system 2.1.11
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
#  - 1.8.7
script: rake test
service_name: travis-pro
repo_token: g0SL8Z1V4FvQWXS0SBAN66xSnt7kDWSH9