language: ruby
before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version
bundler_args: --without development
rvm:
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7
script: rake test
